before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/frk
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
brews:
  - tap:
      owner: winebarrel
      name: homebrew-frk
    homepage: https://github.com/winebarrel/frk
    description: frk is summary generator for your GitHub activities.
    license: MIT
    install: |
      bin.install 'frk'
